name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*' 

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier

      - name: Create .prettierrc
        run: |
          echo '{
            "tabWidth": 4,
            "semi": true
          }' > .prettierrc
      - name: check .prettierrc content
        run: cat .prettierrc
      - name: Run Prettier
        run: npx prettier --write .
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:

     - name: checkout code
       uses: actions/checkout@v4
      
     - name: log into dockerhub
       uses: